package com.example.horoscopelovecalculator

import android.content.Intent
import android.health.connect.datatypes.units.Percentage
import android.os.Bundle
import android.view.ViewGroup
import android.widget.ArrayAdapter
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.example.horoscopelovecalculator.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        Spinners() // to implement Spinners function
        //connecting buttons to function and setting event listener
        binding.button.setOnClickListener { PercentageCompatibility() }
        binding.button2.setOnClickListener { showDetails() }

        popup() //to run popup function

    }

    //For custom popup
    private fun popup() {
        // Inflating my custom layout
        val dialogView = layoutInflater.inflate(R.layout.popup, null) //connected to popup xml

        // Context should be specified when creating AlertDialog.Builder
        // '
        val aboutDialog = AlertDialog.Builder(this)
            .setView(dialogView)

            //dismiss to close popup
            .setPositiveButton("Got it") { dialog, _ ->
                dialog.dismiss()
            }
            .create()//create pop up

        // Setting the dialog animations for smooth feels
        aboutDialog.window?.attributes?.windowAnimations = R.style.DialogAnimation

        // to show the dialog
        aboutDialog.show()
    }


    //impleminting array for the spinners
    private fun Spinners() {
        val zodiacs = arrayOf(
            "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
            "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"
        )
        val adapter = ArrayAdapter(
            this,
            android.R.layout.simple_spinner_dropdown_item,
            zodiacs
        )
        binding.Spinner1.adapter = adapter
        binding.Spinner2.adapter = adapter
    }

    //  A function to show percentage of the pair
    private fun PercentageCompatibility() {
        //defining selected item from spinner
        val firstSign = binding.Spinner1.selectedItem.toString()
        val secondSign = binding.Spinner2.selectedItem.toString()

        // Fetching the compatibility score based on selected zodiac signs
        val score = CompatibilityScore(firstSign, secondSign)

        // Updating the TextView to display the compatibility percentage
        binding.Result.text = "$score%"
    }

    // Storing the combination result and data
    private fun CompatibilityScore(firstSign: String, secondSign: String): Int? {
        val compatibilityMap = mapOf(
            "Aries" to mapOf("Aries" to 90, "Taurus" to 45, "Gemini" to 80, "Cancer" to 45, "Leo" to 90, "Virgo" to 45, "Libra" to 65, "Scorpio" to 50, "Sagittarius" to 90, "Capricorn" to 40, "Aquarius" to 70, "Pisces" to 25),
            "Taurus" to mapOf("Aries" to 45, "Taurus" to 90, "Gemini" to 20, "Cancer" to 96, "Leo" to 35, "Virgo" to 85, "Libra" to 30, "Scorpio" to 65, "Sagittarius" to 25, "Capricorn" to 95, "Aquarius" to 40, "Pisces" to 90),
            "Gemini" to mapOf("Aries" to 80, "Taurus" to 20, "Gemini" to 85, "Cancer" to 15, "Leo" to 85, "Virgo" to 30, "Libra" to 75, "Scorpio" to 10, "Sagittarius" to 99, "Capricorn" to 10, "Aquarius" to 95, "Pisces" to 5),
            "Cancer" to mapOf("Aries" to 45, "Taurus" to 96, "Gemini" to 15, "Cancer" to 90, "Leo" to 25, "Virgo" to 80, "Libra" to 25, "Scorpio" to 79, "Sagittarius" to 30, "Capricorn" to 85, "Aquarius" to 10, "Pisces" to 89),
            "Leo" to mapOf("Aries" to 90, "Taurus" to 35, "Gemini" to 85, "Cancer" to 25, "Leo" to 75, "Virgo" to 30, "Libra" to 80, "Scorpio" to 25, "Sagittarius" to 80, "Capricorn" to 25, "Aquarius" to 60, "Pisces" to 10),
            "Virgo" to mapOf("Aries" to 45, "Taurus" to 85, "Gemini" to 30, "Cancer" to 80, "Leo" to 30, "Virgo" to 70, "Libra" to 40, "Scorpio" to 95, "Sagittarius" to 25, "Capricorn" to 80, "Aquarius" to 25, "Pisces" to 95),
            "Libra" to mapOf("Aries" to 65, "Taurus" to 30, "Gemini" to 75, "Cancer" to 25, "Leo" to 80, "Virgo" to 40, "Libra" to 79, "Scorpio" to 25, "Sagittarius" to 75, "Capricorn" to 30, "Aquarius" to 70, "Pisces" to 25),
            "Scorpio" to mapOf("Aries" to 50, "Taurus" to 65, "Gemini" to 10, "Cancer" to 79, "Leo" to 25, "Virgo" to 95, "Libra" to 25, "Scorpio" to 65, "Sagittarius" to 80, "Capricorn" to 70, "Aquarius" to 30, "Pisces" to 83),
            "Sagittarius" to mapOf("Aries" to 90, "Taurus" to 25, "Gemini" to 99, "Cancer" to 30, "Leo" to 80, "Virgo" to 25, "Libra" to 75, "Scorpio" to 80, "Sagittarius" to 80 , "Capricorn" to 35, "Aquarius" to 80, "Pisces" to 67),
            "Capricorn" to mapOf("Aries" to 40, "Taurus" to 95, "Gemini" to 10, "Cancer" to 85, "Leo" to 25, "Virgo" to 80, "Libra" to 30, "Scorpio" to 70, "Sagittarius" to 35, "Capricorn" to 80, "Aquarius" to 76, "Pisces" to 80),
            "Aquarius" to mapOf("Aries" to 70, "Taurus" to 40, "Gemini" to 95, "Cancer" to 10, "Leo" to 60, "Virgo" to 25, "Libra" to 70, "Scorpio" to 30, "Sagittarius" to 30, "Capricorn" to 76, "Aquarius" to 80, "Pisces" to 45),
            "Pisces" to mapOf("Aries" to 25, "Taurus" to 90, "Gemini" to 5, "Cancer" to 89, "Leo" to 10, "Virgo" to 95, "Libra" to 25, "Scorpio" to 83, "Sagittarius" to 67, "Capricorn" to 80, "Aquarius" to 45, "Pisces" to 75)

        )
        return compatibilityMap[firstSign]?.get(secondSign)//returns the data
    }



    // storing more info for each pair
    private fun CompatibilityDetails(firstSign: String, secondSign: String): String? {
        val detailsMap = mapOf(
            Pair("Aries", "Aries") to "Aries is searching for a fun-loving, impulsive companion. Of course, who could make a better mate than another Aries? These two Aries couples want to be free and independent in a relationship; they don't want to feel constrained. Nobody on this planet can truly comprehend Aries until Aries understands Aries. Aries people have a propensity to live in the now and not worry about the future. ",
            Pair("Aries", "Taurus") to "There isn't much compatibility between Aries and Taurus. Despite their many similarities, they are not going to be a perfect match. They refuse to make concessions and are stubborn. Both Taurus and Aries like to do things their way. They must work at their connection and make concessions for their disagreements. If not, their love won't endure very long.",
            Pair("Aries", "Gemini") to "Aries and Gemini compatibility is high. These zodiac signs make a great match. They may have heated arguments, but as long as they treat one other with respect, their relationship will succeed.",
            Pair("Aries", "Cancer") to "These two signs are not a good combination. Aries people enjoy unpredictability, and Cancer people prefer a secure and nurturing atmosphere. Because the emotional demands of both signs are so dissimilar, a Cancer Aries pairing is out of balance. An Aries Cancer partnership will ultimately struggle to endure.",
            Pair("Aries", "Leo") to "An Aries and a Leo will make a lively and stimulating friendship. They will go on many adventures together once they get together. These two signs will remain faithful to one another, although they may find it difficult to communicate. Both of them are stubborn, believe they are always correct and feel awkward discussing their emotions. Nevertheless, because they are both fire signs, Aries and Leo will complement each other nicely overall.",
            Pair("Aries", "Virgo") to "Aries and Virgo make a potentially compatible pair. Ultimately, the nature of these signs differs greatly. While Aries falls in love quickly, Virgos takes their time. Both as friends and as partners, they will laugh and quarrel a lot. Overall, an Aries Virgo couple could work. If both of them are prepared to make changes, they will get along well.",
            Pair("Aries", "Libra") to "The compatibility of Aries and Libra isn't as obvious as you might believe. There are several advantages and disadvantages to a partnership between these two signs. Even though they don't share many interests, they work well together. They might forge a connection or partnership that lasts a lifetime. All they need to do is learn how to communicate honestly, to accept one another's differences, and to compromise.",
            Pair("Aries", "Scorpio") to "Fire and water signs tend to clash. The compatibility of Aries and Scorpio is average. These zodiac signs don't create the ideal partnership, despite their natural similarities. They will want things done their way because they are both obstinate and passionate. They won't be able to compromise easily when they get into arguments. Tension and animosity may result from their shared belief that they are always correct.",
            Pair("Aries", "Sagittarius") to "With Sagittarius' boundless energy and Aries's penchant for leadership, they will always enjoy themselves no matter what they do.\nTheir mutual understanding of characters will make it easier for them to trust one another and prevent problems from arising frequently.",
            Pair("Aries", "Capricorn") to "Compatibility between Aries and Capricorn is low. These signs are complete opposites. But at times opposites do attract. They collaborate well. Aries and Capricorns can enjoy a decent friendship (or relationship) if they can set aside their differences. But they will swiftly burn out if they become irritated by these kinds of differences.",
            Pair("Aries", "Aquarius") to "As friends or friends with benefits, Aries and Aquarius make a better combination than a possible love pair. Because of their shared ideals and outlook on life, Aries and Aquarius can actually get along well with each other. They just \"get\" one another. These two zodiac signs are naturally adept at conversing and establishing relationships. Both signs are intelligent, creative individuals who are always in need of stimulation. Both Aquarius and Aries enjoy engaging in debates, but Aquarius prefers to keep things reasonable and pragmatic, while Aries will get emotional and confrontational. Just be mindful of the fact that both Aries and Aquarius have strong tempers—Aries more so than Aquarius. ",
            Pair("Aries", "Pisces") to "The compatibility between Pisces and Aries is quite low. It will be difficult for both of these signs to keep a connection continuing. They aren't emotionally compatible with one another. They may have engaging talks, but they won't be able to put their trust in one another or be open with one another. They will have to put in extra effort if they hope to succeed as a relationship.",

            Pair("Taurus", "Aries") to "There isn't much compatibility between Aries and Taurus. Despite their many similarities, they are not going to be a perfect match. They refuse to make concessions and are stubborn. Both Taurus and Aries like to do things their way. They must work at their connection and make concessions for their disagreements. If not, their love won't endure very long.",
            Pair("Taurus", "Taurus") to "The compatibility between Taurus and Taurus is quite strong. These zodiac signs make a wonderful couple. Physically, emotionally, and spiritually, they get along well. Together, they will laugh, weep, and create priceless memories. One of the strongest combinations you may come across is Taurus and Taurus. As friends or lovers, they may have a lifetime together.",
            Pair("Taurus", "Gemini") to "There will be little to no love or affection in a Taurus and Gemini relationship, along with a lot of miscommunication and difficulties. Actually, they get along better as friends than as lovers, and even then, they could be wary of one another. Due to their significant differences, Taurus and Gemini will find it difficult to operate together. ",
            Pair("Taurus", "Cancer") to "One of the zodiac signs' strongest pairings is Taurus and Cancer. Both of these signs don't hesitate to show their emotions. They will own up to it when they're not feeling well. When they're upset, they'll give an explanation. They will not miscommunicate since they are so honest about how they are feeling. They will be able to resolve any issues that may develop since they will always be aware of what is going through the other person's head. Their relationship will remain solid as long as they communicate.",
            Pair("Taurus", "Leo") to "It is best to stay away from Taurus and Leo relationships at all costs. Despite being two very different astrological signs, their stubbornness is similar because they are both fixed signs. As a couple, Taurus and Leo may encounter problems that are highly hostile. They will find it challenging to communicate, particularly when it comes to their feelings and thoughts. In a Taurus Leo partnership, pride is a problem because both signs are quite independent and self-centered.",
            Pair("Taurus", "Virgo") to "Both Taurus and Virgos are signs of nurturing. It will take some time for their relationship to develop because they tend to take things gently in partnerships. But as soon as they are formally a couple, they will look out for one another. Taurus and Virgos will assist one another with household tasks. When it comes to their professional goals and personal development, they will support one another and listen to one other complain. Taurus and Virgo will work well together. If they collaborate, they will achieve great things.",
            Pair("Taurus", "Libra") to "Unfortunately, there is not much compatibility between Taurus and Libra. It's not the greatest fit for these two signs. But if they work hard to learn how to talk to each other, they can work out a connection. If not, the partnership will dissolve very rapidly. These signs are just too different.",
            Pair("Taurus", "Scorpio") to "Astrologically, we have two opposite signs on the zodiac wheel: Taurus and Scorpio. Scorpio is a water sign and Taurus is an earth sign. Nonetheless, they appear to be rather compatible and are fairly similar despite their positions in the zodiac.  They will not disappoint one another. They will encourage, push, and support one another as they go on. Furthermore, in order to remain a constant in each other's lives, they both want for safe, permanent relationships.",
            Pair("Taurus", "Sagittarius") to "There is very little compatibility between Sagittarius and Taurus. These signs of the zodiac are total opposites. Whereas Sagittarius yearns for change, Taurus loves routine. They may argue a great deal as a result of this. Both parties in a Taurus Sagittarius relationship must be forthright about their boundaries for the partnership to succeed. Even though they might not fully comprehend their partner's requirements, they nevertheless need to show respect for them.",
            Pair("Taurus", "Capricorn") to "There is a very good compatibility between Taurus and Capricorn. These two zodiac signs are sensible, trustworthy, and analytical. They always keep their word and are trustworthy as well. They don't think it's acceptable to mislead or fool those closest to them. Taurus and Capricorn have a lot in common, which makes them a great combination.",
            Pair("Taurus", "Aquarius") to "The compatibility between Taurus and Aquarius is extremely low. Seldom do these two signs get along. They are extremely different. They won't last as a pair if they can't compromise and be open to changing their minds when they disagree. They may not even remain friends.",
            Pair("Taurus", "Pisces") to "These two signs are a match made in heaven since they both place a high importance on deep emotional relationships. They find it difficult to part from someone once they become attached to them. They won't automatically want to leave if there is a problem. It will be to mend the connection, reach a compromise, and make apologies. ",

            Pair("Gemini", "Aries") to "Aries and Gemini compatibility is high. These zodiac signs make a great match. They may have heated arguments, but as long as they treat one other with respect, their relationship will succeed.",
            Pair("Gemini", "Taurus") to "There will be little to no love or affection in a Taurus and Gemini relationship, along with a lot of miscommunication and difficulties. Actually, they get along better as friends than as lovers, and even then, they could be wary of one another. Due to their significant differences, Taurus and Gemini will find it difficult to operate together. ",
            Pair("Gemini", "Gemini") to "The compatibility between Geminis is rather strong. Two Geminis will get along well, despite the fact that they will struggle to trust each other. They will always have interesting discussions because they hold similar values and opinions. Additionally, they share similar interests and pastimes, so they'll always find something fascinating to do on the weekends.",
            Pair("Gemini", "Cancer") to "Cancer and Gemini are not very compatible. If these zodiac signs are to have a successful partnership, they must make significant changes. They will misunderstand each other a lot if they don't. Cancer and Gemini are total opposites. Their priorities, values, and morals are dissimilar. Their expectations from a partnership are not the same.",
            Pair("Gemini", "Leo") to "Despite their differences, these signs may benefit from their contrasting characteristics. For example, Geminis struggle with even the most basic decisions. They are never sure where to go or what to eat. As for their hangouts, Leos can make the plans because they enjoy taking the lead. Geminis don't have to consider the advantages and disadvantages of each choice thanks to Leos. They can also assist a Gemini in stopping second-guessing by giving them confidence in their choice.",
            Pair("Gemini", "Virgo") to "Two of the zodiac signs that are flexible and have excellent communication skills are Gemini and Virgo. However, that doesn't always imply that they would be a good romantic or platonic partner. They will find it difficult to trust one another in a serious relationship. A Virgo, after all, wants a companion who will be steady, dependable, and a constant. No matter what, they need to feel they can always count on their partner. A Gemini, meanwhile, is difficult to pin down. They want to go on adventures, explore new towns, and make out with new individuals. A committed, monogamous relationship isn't actually what they're interested in.",
            Pair("Gemini", "Libra") to "The Libra-Gemini bond is strong and relies on enjoyment. They are individuals that enjoy interacting with others.Both signs are perceptive and full of creative ideas and activities. They will also inspire one another! With the indecisive and people-pleaser Libra buddy and the unreliable and erratic Gemini companion, they may occasionally run across obstacles. It's nothing, though, that they can't resolve together.",
            Pair("Gemini", "Scorpio") to "Compatibility between Gemini and Scorpio is low. These signs use various idioms to convey their feelings. Since their communication styles are so dissimilar, they will find it difficult to communicate with one another. But with enough perseverance, these indicators might overcome the difficulties and have a successful marriage.",
            Pair("Gemini", "Sagittarius") to "Given that both of these fire and air signs place a high importance on faithfulness and trust, a love relationship between them will have a solid foundation built on these qualities. Both signs have a great deal of empathy for one another's passions and life principles. They are good companions despite being opposite signs, provided they resolve issues together.",
            Pair("Gemini", "Capricorn") to "Capricorn and Gemini are not very compatible. There is nearly no overlap between these two indications. Relationships or friendships between Gemini and Capricorn never endure more than a few days. But if they both work hard at it, it could work. These indications must be upfront and honest with one another from the beginning if they hope to survive a lifetime. They must articulate their goals in unambiguous terms.",
            Pair("Gemini", "Aquarius") to "Given that both of these signals entail emotional difficulties, there may be some challenges ahead.They don’t like to dwell on the way they are feeling and would rather push uncomfortable emotions deep down in their chest.  They won't hold it against each other, though, since they both find it difficult to be vulnerable. If there are a few secrets here and there, they'll understand. Additionally, they will be understanding if the other person isn't feeling inclined to discuss their problems. The partnership won't end because of the lack of communication.",
            Pair("Gemini", "Pisces") to "There is very little compatibility between Gemini and Pisces. These are some of the worst conceivable combinations of zodiac signs. Physically, intellectually, or emotionally, they are incompatible. They don't communicate well with each other. They will avoid talking about their emotions at all costs. ",

            Pair("Cancer", "Aries") to "These two signs are not a good combination. Aries people enjoy unpredictability, and Cancer people prefer a secure and nurturing atmosphere. Because the emotional demands of both signs are so dissimilar, a Cancer Aries pairing is out of balance. An Aries Cancer partnership will ultimately struggle to endure.",
            Pair("Cancer", "Taurus") to "One of the zodiac signs' strongest pairings is Taurus and Cancer. Both of these signs don't hesitate to show their emotions. They will own up to it when they're not feeling well. When they're upset, they'll give an explanation. They will not miscommunicate since they are so honest about how they are feeling. They will be able to resolve any issues that may develop since they will always be aware of what is going through the other person's head. Their relationship will remain solid as long as they communicate.",
            Pair("Cancer", "Gemini") to "Cancer and Gemini are not very compatible. If these zodiac signs are to have a successful partnership, they must make significant changes. They will misunderstand each other a lot if they don't. Cancer and Gemini are total opposites. Their priorities, values, and morals are dissimilar. Their expectations from a partnership are not the same.",
            Pair("Cancer", "Cancer") to "The compatibility between cancer and cancer is very strong. Because they complement each other both physically and emotionally, two Cancers form a fantastic combination. When they're together, they'll never feel abandoned because they'll both work very hard. They won't share everything, but they will connect on the most significant things.",
            Pair("Cancer", "Leo") to "Leos who are so forward-thinking make Cancers uncomfortable. They act in opposing ways as well. For cancers, actions speak louder than words. They'll demonstrate their affection with acts of service. Leos, however, will seek words of affirmation. They'll demand continuous recognition. When it comes to how they wish to be loved, Cancer and Leo are worlds apart.",
            Pair("Cancer", "Virgo") to "The heart and the mind are highly connected for Cancer and Virgo. Both Virgo and Cancer are open to letting the other in to see who they really are, and they both enjoy learning from each other and their differences. This type of pair may occasionally find it difficult to communicate, even though one of them will always be more adept at it than the other. When it comes time to approach Virgo, Cancer will probably find it difficult, while Virgo finds communication easy. Whereas Cancer will be emotional, loving, and full of excessive expectations, Virgo will be analytical and logical yet still nurturing.",
            Pair("Cancer", "Libra") to "While Cancer will view their attractive Libra as too unreliable for commitment, Libra will believe their partner's expectations of a relationship are a little too high. Cancer needs to have deep, in-depth conversations with their partner before taking the next step in the relationship.  Libra, on the other hand, prefers to flirt first and establish a deeper emotional bond afterward. Their definitions of affection are quite different.",
            Pair("Cancer", "Scorpio") to "True love between a Scorpio and a Cancer companion is based on communication and trust. Instead of having numerous flings, they would like to be in a faithful, committed relationship with their soul mate. Whereas a Cancer will desire for stability in a relationship, a Scorpio will want for power. There won't be any concerns about cheating because both of these signs are both quite faithful. But in the event of an emergency, it would be sufficiently natural for the Scorpio and the Cancer to be open and honest with one another. ",
            Pair("Cancer", "Sagittarius") to "It's not optimal for Cancer and Sagittarius to be romantically involved. It is unlikely that both of these signs will be drawn to one other. Just as Sagittarius' enormous ego and need for attention from others would irritate their Cancer companion, Cancer's jealously and possessiveness will be too much for their Sagittarius mate. It might be draining for Sagittarius and Cancer to be in a relationship because of their unpredictable nature.",
            Pair("Cancer", "Capricorn") to "Capricorns are afraid of being committed. They like to wait to start a relationship until they are certain it will endure. Fortunately, a Cancer can be trusted because they both have a strong sense of loyalty. They wish to be in a committed, long-term relationship with a special someone. These two signs would both prefer to be contentedly married and committed to one another than to have periodic affairs.",
            Pair("Cancer", "Aquarius") to "Even though both signs like social situations, a Cancer will eventually wish to withdraw within their home, much like a crab does in its shell. An Aquarian will want to continue and stay outside in the interim. They both have the disposition to expect things to go their way. Whereas Aquarius will use their independence and knowledge to make decisions that work for them alone, Cancer will resort to manipulation. They must resolve their differences in order for their friendship to be strong.",
            Pair("Cancer", "Pisces") to "Cancers and Pisces have loyalty. They keep their word when they commit to someone. More importantly, they are at ease discussing everything and everything, so they will never run out of things to talk about. They'll talk about their futures, reveal their deepest fears, and share secrets. There aren’t any topics that are off limits when it comes to these two signs.",

            Pair("Leo", "Aries") to "An Aries and a Leo will make a lively and stimulating friendship. They will go on many adventures together once they get together. These two signs will remain faithful to one another, although they may find it difficult to communicate. Both of them are stubborn, believe they are always correct and feel awkward discussing their emotions. Nevertheless, because they are both fire signs, Aries and Leo will complement each other nicely overall.",
            Pair("Leo", "Taurus") to "It is best to stay away from Taurus and Leo relationships at all costs. Despite being two very different astrological signs, their stubbornness is similar because they are both fixed signs. As a couple, Taurus and Leo may encounter problems that are highly hostile. They will find it challenging to communicate, particularly when it comes to their feelings and thoughts. In a Taurus Leo partnership, pride is a problem because both signs are quite independent and self-centered.",
            Pair("Leo", "Gemini") to "Despite their differences, these signs may benefit from their contrasting characteristics. For example, Geminis struggle with even the most basic decisions. They are never sure where to go or what to eat. As for their hangouts, Leos can make the plans because they enjoy taking the lead. Geminis don't have to consider the advantages and disadvantages of each choice thanks to Leos. They can also assist a Gemini in stopping second-guessing by giving them confidence in their choice.",
            Pair("Leo", "Cancer") to "Leos who are so forward-thinking make Cancers uncomfortable. They act in opposing ways as well. For cancers, actions speak louder than words. They'll demonstrate their affection with acts of service. Leos, however, will seek words of affirmation. They'll demand continuous recognition. When it comes to how they wish to be loved, Cancer and Leo are worlds apart.",
            Pair("Leo", "Leo") to "Compatibility between Leos lies in the center. These couples will argue a lot, even though they share a lot of things. Two Leos must address their trust concerns if they hope to have a successful partnership. They must be faithful to one another and make a commitment to one another. They can't let their jealousy destroy their bond.",
            Pair("Leo", "Virgo") to "Although the compatibility between Leo and Virgo is low, their relationships have benefits. Leos will feel unique since Virgos will notice small characteristics about them. But Virgos aren't one to pull out elaborate, passionate gestures. They are so subtle and realistic in their deeds of love that sometimes Leo will never know how hard they've worked. Worse, occasionally Virgos flirt by drawing attention to their shortcomings. Leo is going to get annoyed and feel hurt by this.",
            Pair("Leo", "Libra") to "Leo and Libra are different zodiac signs, yet they still have a lot in common and might be a great friendship and love match. They must be patient and open with one another about their wants for it to succeed. Leos enjoys taking charge and grabbing attention. Because they like to please others, Libras will give in to their demands as long as it maintains harmony.When a Libra gets angry, they tend to appear self-pitying or passive-aggressive, whereas a Leo becomes obstinate, brutally honest, and self-centered. Both Leo and Libra have a lot to teach one another. While a Libra is calm, a Leo is strong and untamed; these contrasts can counterbalance one another.",
            Pair("Leo", "Scorpio") to "Because Leo Scorpios have such distinct and powerful personalities, relationships involving them will be extremely difficult. It's possible that neither sign would fare well in a relationship, much less on a date. In addition, the Leo lover leads with confidence, ardor, and occasionally even a carefree attitude, whereas the Scorpio lover leads with depth and feelings.",
            Pair("Leo", "Sagittarius") to "Two fire signs go together quite well. Their love for life and vitality are the same. Sagittarius and Leo have similar personalities. These fire signs complement each other well. Love in Leo Sagittarius can be powerful, but it requires effort. They must appreciate one another, be faithful, and improve their communication abilities. They will become disinterested otherwise. A Sagittarius and Leo couple must put in a lot of effort to maintain their strong bond.",
            Pair("Leo", "Capricorn") to "Because they are independent, Capricorns seek a mate who shares their commitment to self-care. But Leos like to be pampered. They want their spouses to be in charge, even when they are capable of handling things on their own. They want to be treated and then sit back and unwind. For them, having support from someone else is the ultimate goal of a relationship.",
            Pair("Leo", "Aquarius") to "Despite having very different priorities, these two signs can nonetheless operate together in a friendship. Their differences simply cannot be allowed to get in the way of their relationship. They are really loyal to one other, after all. They would stop at nothing to help someone with whom they had a connection. Those they adore are zealously protected by them. These indicators are also quite aspirational. They don't give up on goals they set for themselves. They don't give up until they achieve their objectives.",
            Pair("Leo", "Pisces") to "Because Leo Pisces pursues two very distinct kind of love, their partnership is incredibly flawed. Leo will seem to Pisces too detached from their feelings, while Pisces will perceive their Leo partner as too cut off from their own ambitions and strengths. The Pisces spouse will lack strength, confidence, and initiative, whereas Leo will come across as blunt, honest, and insensitive. In a Leo Pisces relationship, there will be a lot of miscommunication and disrespect, which will ultimately cause them to break up.",

            Pair("Virgo", "Aries") to "Aries and Virgo make a potentially compatible pair. Ultimately, the nature of these signs differs greatly. While Aries falls in love quickly, Virgos takes their time. Both as friends and as partners, they will laugh and quarrel a lot. Overall, an Aries Virgo couple could work. If both of them are prepared to make changes, they will get along well.",
            Pair("Virgo", "Taurus") to "Both Taurus and Virgos are signs of nurturing. It will take some time for their relationship to develop because they tend to take things gently in partnerships. But as soon as they are formally a couple, they will look out for one another. Taurus and Virgos will assist one another with household tasks. When it comes to their professional goals and personal development, they will support one another and listen to one other complain. Taurus and Virgo will work well together. If they collaborate, they will achieve great things.",
            Pair("Virgo", "Gemini") to "Two of the zodiac signs that are flexible and have excellent communication skills are Gemini and Virgo. However, that doesn't always imply that they would be a good romantic or platonic partner. They will find it difficult to trust one another in a serious relationship. A Virgo, after all, wants a companion who will be steady, dependable, and a constant. No matter what, they need to feel they can always count on their partner. A Gemini, meanwhile, is difficult to pin down. They want to go on adventures, explore new towns, and make out with new individuals. A committed, monogamous relationship isn't actually what they're interested in.",
            Pair("Virgo", "Cancer") to "The heart and the mind are highly connected for Cancer and Virgo. Both Virgo and Cancer are open to letting the other in to see who they really are, and they both enjoy learning from each other and their differences. This type of pair may occasionally find it difficult to communicate, even though one of them will always be more adept at it than the other. When it comes time to approach Virgo, Cancer will probably find it difficult, while Virgo finds communication easy. Whereas Cancer will be emotional, loving, and full of excessive expectations, Virgo will be analytical and logical yet still nurturing.",
            Pair("Virgo", "Leo") to "Although the compatibility between Leo and Virgo is low, their relationships have benefits. Leos will feel unique since Virgos will notice small characteristics about them. But Virgos aren't one to pull out elaborate, passionate gestures. They are so subtle and realistic in their deeds of love that sometimes Leo will never know how hard they've worked. Worse, occasionally Virgos flirt by drawing attention to their shortcomings. Leo is going to get annoyed and feel hurt by this.",
            Pair("Virgo", "Virgo") to "The virgo personality type is known for their intense caring, and they are looking for a companion who will value their critical thinking. Virgo's critical and perhaps harsh remarks might cause a partner to feel as though they aren't good enough for Virgo and that they need to put in more work before they can live up to their expectations. But, in a partnership between two critical Virgos, they will undoubtedly comprehend each other's thought processes and pushing styles because they share such traits.",
            Pair("Virgo", "Libra") to "When it comes to feelings, these two will not get along. Their inability to communicate their feelings to each other could be the end of their relationship. Nobody will bring up any issues in this connection between Virgo and Libra. Every marriage will argue from time to time, but if/when Virgo and Libra get to that stage, it will get messy because Virgo becomes judgmental and critical, while Libra becomes manipulative and passive-aggressive. They will politely deal with the issues if they have sufficient respect for one another and the relationship. ",
            Pair("Virgo", "Scorpio") to "Scorpios and Virgos can have in-depth, meaningful discussions about their own lives, their feelings, and mankind at large. These signs can cognitively excite, instruct, and challenge one another. They are aware of the power of quiet, though. These signs get along so well that they can just sit and do nothing without feeling uncomfortable. It's cozy in the stillness. They enjoy themselves without feeling compelled to talk during the quiet moments.",
            Pair("Virgo", "Sagittarius") to "Sagittarius and Virgos aren't usually compatible. Their lifestyles are radically dissimilar. Virgos want to consider their options carefully before acting. They will examine issues, circumstances, and individuals from every viewpoint that they can. Knowledge is important to Virgos, and they take great satisfaction in acting morally. Conversely, Sagittarius is one of the zodiac signs that is most impulsive. Instead of taking the safe road, they would prefer to take the adventurous one. The proper course of action doesn't matter to them. Their main priority is to enjoy themselves. A Virgo is seen as a downer by a Sagittarius since they tend to follow their common sense rather than their instincts.",
            Pair("Virgo", "Capricorn") to "There will be a solid, dependable association between these signs. They will remain faithful because none of them wants to cheat. They intend to honor their commitments. They will both be content to adhere to a schedule that they establish together. For them to be content, no wild and crazy adventures will be necessary. Virgo and Capricorn would much rather stay in their comfort zones because that is where they feel most at ease. Rather than a passionate relationship, they desire stability.",
            Pair("Virgo", "Aquarius") to "If these two signs hope to maintain a love connection, they will need to put in a lot of effort. They will have to work at talking to each other and making concessions to one another. The relationship won't endure long if they let their stubbornness or tempers to get the better of them. These two signs do, after all, want to follow their own set of rules. Even their lover doesn't have the right to dictate to them what to do.",
            Pair("Virgo", "Pisces") to "Virgos benefit from the influence of Pisces. They can greatly improve a Virgo's ability to connect with their emotions. Virgos, after all, have a nasty habit of ignoring unpleasant emotions and diverting their attention with activity. But a Pisces will demonstrate to a Virgo that they don't need to isolate oneself in order to be safe. A Virgo will be encouraged by a Pisces to be much more open and at ease with their own feelings.",

            Pair("Libra", "Aries") to "The compatibility of Aries and Libra isn't as obvious as you might believe. There are several advantages and disadvantages to a partnership between these two signs. Even though they don't share many interests, they work well together. They might forge a connection or partnership that lasts a lifetime. All they need to do is learn how to communicate honestly, to accept one another's differences, and to compromise.",
            Pair("Libra", "Taurus") to "Unfortunately, there is not much compatibility between Taurus and Libra. It's not the greatest fit for these two signs. But if they work hard to learn how to talk to each other, they can work out a connection. If not, the partnership will dissolve very rapidly. These signs are just too different.",
            Pair("Libra", "Gemini") to "The Libra-Gemini bond is strong and relies on enjoyment. They are individuals that enjoy interacting with others.Both signs are perceptive and full of creative ideas and activities. They will also inspire one another! With the indecisive and people-pleaser Libra buddy and the unreliable and erratic Gemini companion, they may occasionally run across obstacles. It's nothing, though, that they can't resolve together.",
            Pair("Libra", "Cancer") to "While Cancer will view their attractive Libra as too unreliable for commitment, Libra will believe their partner's expectations of a relationship are a little too high. Cancer needs to have deep, in-depth conversations with their partner before taking the next step in the relationship.  Libra, on the other hand, prefers to flirt first and establish a deeper emotional bond afterward. Their definitions of affection are quite different.",
            Pair("Libra", "Leo") to "Leo and Libra are different zodiac signs, yet they still have a lot in common and might be a great friendship and love match. They must be patient and open with one another about their wants for it to succeed. Leos enjoys taking charge and grabbing attention. Because they like to please others, Libras will give in to their demands as long as it maintains harmony.When a Libra gets angry, they tend to appear self-pitying or passive-aggressive, whereas a Leo becomes obstinate, brutally honest, and self-centered. Both Leo and Libra have a lot to teach one another. While a Libra is calm, a Leo is strong and untamed; these contrasts can counterbalance one another.",
            Pair("Libra", "Virgo") to "When it comes to feelings, these two will not get along. Their inability to communicate their feelings to each other could be the end of their relationship. Nobody will bring up any issues in this connection between Virgo and Libra. Every marriage will argue from time to time, but if/when Virgo and Libra get to that stage, it will get messy because Virgo becomes judgmental and critical, while Libra becomes manipulative and passive-aggressive. They will politely deal with the issues if they have sufficient respect for one another and the relationship. ",
            Pair("Libra", "Libra") to "Relationships between Libras are smooth. They have a pretty good friendship and relationship together. Long-term relationships, whether romantic or platonic, may result from a Libra love connection. Libras can coexist peacefully as long as they make time to discuss their partner's emotional needs as well as their own, as well as to talk about the aspects of their personalities that they so much wish to keep hidden from the outside world.",
            Pair("Libra", "Scorpio") to "It will be difficult for these two signs to trust one another. Scorpios desire exclusive attention from their mate. But Libras desire to be loved by everyone. They will invest the same time and energy in their friendships and professional relationships as they do in their relationship with their partner. A Scorpio is not going to take well to it. Scorpios are far too protective to be in a relationship with someone who is looking for approval from others. When they are the only ones who are happy with them, they will function considerably better.",
            Pair("Libra", "Sagittarius") to " Libra Friendships with Sagittarius will be strong and well-balanced. Achievements and knowledge excite the curiosity of both signs. Libra can help Sagittarius hone their intellect since they are constantly seeking knowledge and opportunities to explore new things. Together, they're going to go on amazing, once-in-a-lifetime experiences. Because Sagittarius despises routine, they will always think of exciting things to do. Because Libras like to satisfy others, they won't decline an invitation. ",
            Pair("Libra", "Capricorn") to "The compatibility of Capricorn and Libra is low. The priorities and values of these two signs are different. Libras are very conscious of how other people perceive them. In the meantime, Capricorn doesn't give any thought about what people think. Despite their differences, these two signs are capable of making a relationship work if they work hard at it.",
            Pair("Libra", "Aquarius") to "These two signs of the zodiac are eager to discover the world's natural beauties. Libras and Aquarians like socializing with new people and expanding their knowledge of the cosmos. Their appetite for information and experience is strong. These two signs are social butterflies who will make great pals. When given the chance, Aquarius and Libra will never say no to a road trip, concert, or party. They'll be willing to try nearly anything. Their relationship will grow stronger with each adventure they embark on together.",
            Pair("Libra", "Pisces") to "These signs don't go together well. They will hold a lot of their emotions, both positive and negative, inside. They'll never be aware of the other person's thoughts. It gets worse: they won't be able to put their trust in one another. Libras are flirts after all. They enchant everyone they come into contact with. This will not sit well with a Pisces. Pisces seeks a mate who will refrain from making fun of them. They are looking for a mate that is 100 percent devoted.",

            Pair("Scorpio", "Aries") to "Fire and water signs tend to clash. The compatibility of Aries and Scorpio is average. These zodiac signs don't create the ideal partnership, despite their natural similarities. They will want things done their way because they are both obstinate and passionate. They won't be able to compromise easily when they get into arguments. Tension and animosity may result from their shared belief that they are always correct.",
            Pair("Scorpio", "Taurus") to "Astrologically, we have two opposite signs on the zodiac wheel: Taurus and Scorpio. Scorpio is a water sign and Taurus is an earth sign. Nonetheless, they appear to be rather compatible and are fairly similar despite their positions in the zodiac.  They will not disappoint one another. They will encourage, push, and support one another as they go on. Furthermore, in order to remain a constant in each other's lives, they both want for safe, permanent relationships",
            Pair("Scorpio", "Gemini") to "Compatibility between Gemini and Scorpio is low. These signs use various idioms to convey their feelings. Since their communication styles are so dissimilar, they will find it difficult to communicate with one another. But with enough perseverance, these indicators might overcome the difficulties and have a successful marriage.",
            Pair("Scorpio", "Cancer") to "True love between a Scorpio and a Cancer companion is based on communication and trust. Instead of having numerous flings, they would like to be in a faithful, committed relationship with their soul mate. Whereas a Cancer will desire for stability in a relationship, a Scorpio will want for power. There won't be any concerns about cheating because both of these signs are both quite faithful. But in the event of an emergency, it would be sufficiently natural for the Scorpio and the Cancer to be open and honest with one another.",
            Pair("Scorpio", "Leo") to "Because Leo Scorpios have such distinct and powerful personalities, relationships involving them will be extremely difficult. It's possible that neither sign would fare well in a relationship, much less on a date. In addition, the Leo lover leads with confidence, ardor, and occasionally even a carefree attitude, whereas the Scorpio lover leads with depth and feelings.",
            Pair("Scorpio", "Virgo") to "Scorpios and Virgos can have in-depth, meaningful discussions about their own lives, their feelings, and mankind at large. These signs can cognitively excite, instruct, and challenge one another. They are aware of the power of quiet, though. These signs get along so well that they can just sit and do nothing without feeling uncomfortable. It's cozy in the stillness. They enjoy themselves without feeling compelled to talk during the quiet moments.",
            Pair("Scorpio", "Libra") to "It will be difficult for these two signs to trust one another. Scorpios desire exclusive attention from their mate. But Libras desire to be loved by everyone. They will invest the same time and energy in their friendships and professional relationships as they do in their relationship with their partner. A Scorpio is not going to take well to it. Scorpios are far too protective to be in a relationship with someone who is looking for approval from others. When they are the only ones who are happy with them, they will function considerably better.",
            Pair("Scorpio", "Scorpio") to "Scorpios require a ruthlessly truthful companion. Even tiny lies are intolerable to them when they are told. Scorpios require a truth-teller who won't back down from a fight. They also require a committed and strong-willed companion. This sign detests those who are passive. In a relationship, they don't always want to be the one making the decisions. They desire independence from their partner on par with their own. Scorpios value individuality and independence in their relationships. They have no interest in dating their own duplicates. They're looking for someone quite different. ",
            Pair("Scorpio", "Sagittarius") to "Scorpio and Sagittarius share a similar outlook on life, which makes them excellent friends. This fire and water combo may not work well at first, but it will improve with time. There are moments when Sagittarius is a touch too combative and sometimes Scorpio is a little too stubborn for Sagittarius. If or when they argue, they will have to make concessions: Sagittarius must acquire respect and understanding, while Scorpio must learn to relax and control their emotions.",
            Pair("Scorpio", "Capricorn") to "They could be very close friends because of their similar personalities. They are both very devoted, after all. They'd go to great lengths to help a friend in distress. They would never abandon a person in need of assistance. They are also both focused and driven. They will succeed greatly if they collaborate on a project. They'll encourage one another to succeed. Scorpios tend to be possessive of the people in their lives, but since Capricorns are generally faithful, they shouldn't worry about it. Scorpios will follow along with passion and feedback from Capricorns who will take the initiative with fresh ideas. They will be an invincible team as long as they can master appropriate communication techniques and treat one another with respect at all times.",
            Pair("Scorpio", "Aquarius") to "Due to their dissimilar characteristics, this zodiac couple isn't the strongest romantic duo. The unclear emotionally distant Aquarius will find Scorpio's emotions and possessiveness to be excessively intense. Their Aquarian spouse will not want to deal with their Scorpio partner's occasional clinginess and emotional outbursts; instead, their free-spirited nature and incapacity to communicate their feelings will allow them to pack up and walk on. They both need to put in a lot of effort and dedication, communicate their feelings, and have a strong foundation of trust for a romantic relationship to succeed.",
            Pair("Scorpio", "Pisces") to "Both of these signs have a desire for commitment and long-term relationships. Their only desire is to find their soul partner and settle down to enjoy life. Their shared goals in life and their effective communication skills make them a great combination. They have enough faith in one another, to be honest with one another about their feelings and ideas, which is not usually the case with Scorpios. When they are with the wrong person, they will withdraw, but when they are with Pisces, they will feel secure enough to be vulnerable.",

            Pair("Sagittarius", "Aries") to "With Sagittarius' boundless energy and Aries's penchant for leadership, they will always enjoy themselves no matter what they do.\\nTheir mutual understanding of characters will make it easier for them to trust one another and prevent problems from arising frequently.\"",
            Pair("Sagittarius", "Taurus") to "There is very little compatibility between Sagittarius and Taurus. These signs of the zodiac are total opposites. Whereas Sagittarius yearns for change, Taurus loves routine. They may argue a great deal as a result of this. Both parties in a Taurus Sagittarius relationship must be forthright about their boundaries for the partnership to succeed. Even though they might not fully comprehend their partner's requirements, they nevertheless need to show respect for them.",
            Pair("Sagittarius", "Gemini") to "Given that both of these fire and air signs place a high importance on faithfulness and trust, a love relationship between them will have a solid foundation built on these qualities. Both signs have a great deal of empathy for one another's passions and life principles. They are good companions despite being opposite signs, provided they resolve issues together.",
            Pair("Sagittarius", "Cancer") to "It's not optimal for Cancer and Sagittarius to be romantically involved. It is unlikely that both of these signs will be drawn to one other. Just as Sagittarius' enormous ego and need for attention from others would irritate their Cancer companion, Cancer's jealously and possessiveness will be too much for their Sagittarius mate. It might be draining for Sagittarius and Cancer to be in a relationship because of their unpredictable nature.",
            Pair("Sagittarius", "Leo") to "Two fire signs go together quite well. Their love for life and vitality are the same. Sagittarius and Leo have similar personalities. These fire signs complement each other well. Love in Leo Sagittarius can be powerful, but it requires effort. They must appreciate one another, be faithful, and improve their communication abilities. They will become disinterested otherwise. A Sagittarius and Leo couple must put in a lot of effort to maintain their strong bond.",
            Pair("Sagittarius", "Virgo") to "Sagittarius and Virgos aren't usually compatible. Their lifestyles are radically dissimilar. Virgos want to consider their options carefully before acting. They will examine issues, circumstances, and individuals from every viewpoint that they can. Knowledge is important to Virgos, and they take great satisfaction in acting morally. Conversely, Sagittarius is one of the zodiac signs that is most impulsive. Instead of taking the safe road, they would prefer to take the adventurous one. The proper course of action doesn't matter to them. Their main priority is to enjoy themselves. A Virgo is seen as a downer by a Sagittarius since they tend to follow their common sense rather than their instincts.",
            Pair("Sagittarius", "Libra") to " Libra Friendships with Sagittarius will be strong and well-balanced. Achievements and knowledge excite the curiosity of both signs. Libra can help Sagittarius hone their intellect since they are constantly seeking knowledge and opportunities to explore new things. Together, they're going to go on amazing, once-in-a-lifetime experiences. Because Sagittarius despises routine, they will always think of exciting things to do. Because Libras like to satisfy others, they won't decline an invitation. ",
            Pair("Sagittarius", "Scorpio") to "Scorpio and Sagittarius share a similar outlook on life, which makes them excellent friends. This fire and water combo may not work well at first, but it will improve with time. There are moments when Sagittarius is a touch too combative and sometimes Scorpio is a little too stubborn for Sagittarius. If or when they argue, they will have to make concessions: Sagittarius must acquire respect and understanding, while Scorpio must learn to relax and control their emotions.",
            Pair("Sagittarius", "Sagittarius") to "The compatibility between Sagittarius and Sagittarius is excellent. There will be a great deal of compatibility between these zodiac signs. They will have many enjoyable, unexpected experiences together. They will laugh a lot together as well. They will, nevertheless, have trouble communicating. The relationship can deteriorate since they won't be open to talking about their feelings. Two Scorpios must learn to be at ease with one another before they can function as a couple.",
            Pair("Sagittarius", "Capricorn") to "Their lifestyles are too dissimilar for a partnership to succeed. A Sagittarius, for instance, might prefer to go out every weekend, exploring new areas and having novel experiences. A Capricorn, on the other hand, will be happiest curled up with a good book in bed. They have no desire to leave their house. They would prefer to remain indoors and shut out the outside world.",
            Pair("Sagittarius", "Aquarius") to "Both Sagittarius and Aquarius are highly intelligent and cognizant of one another's characteristics. They are unparalleled in their dedication to understanding one another. While the Aquarius companion will contribute unique ideas and stimulating discourse, the Sagittarius partner will add warmth to the partnership. ",
            Pair("Sagittarius", "Pisces") to "Given that Sagittarius and Pisces are two fluid signs, it's possible that they will be excellent friends while having different underlying identities. While both Sagittarius and Pisces possess an analytical and philosophical mind, Sagittarius prefers to be free to jump right into new challenges, while Pisces prefers to go a little bit further into their fantasies. Sagittarius only considers the larger picture that is directly in front of them, whereas Pisces looks to the future.",

            Pair("Capricorn", "Aries") to "Compatibility between Aries and Capricorn is low. These signs are complete opposites. But at times opposites do attract. They collaborate well. Aries and Capricorns can enjoy a decent friendship (or relationship) if they can set aside their differences. But they will swiftly burn out if they become irritated by these kinds of differences.",
            Pair("Capricorn", "Taurus") to "There is a very good compatibility between Taurus and Capricorn. These two zodiac signs are sensible, trustworthy, and analytical. They always keep their word and are trustworthy as well. They don't think it's acceptable to mislead or fool those closest to them. Taurus and Capricorn have a lot in common, which makes them a great combination.",
            Pair("Capricorn", "Gemini") to "Capricorn and Gemini are not very compatible. There is nearly no overlap between these two indications. Relationships or friendships between Gemini and Capricorn never endure more than a few days. But if they both work hard at it, it could work. These indications must be upfront and honest with one another from the beginning if they hope to survive a lifetime. They must articulate their goals in unambiguous terms.",
            Pair("Capricorn", "Cancer") to "Capricorns are afraid of being committed. They like to wait to start a relationship until they are certain it will endure. Fortunately, a Cancer can be trusted because they both have a strong sense of loyalty. They wish to be in a committed, long-term relationship with a special someone. These two signs would both prefer to be contentedly married and committed to one another than to have periodic affairs.",
            Pair("Capricorn", "Leo") to "Because they are independent, Capricorns seek a mate who shares their commitment to self-care. But Leos like to be pampered. They want their spouses to be in charge, even when they are capable of handling things on their own. They want to be treated and then sit back and unwind. For them, having support from someone else is the ultimate goal of a relationship.",
            Pair("Capricorn", "Virgo") to "There will be a solid, dependable association between these signs. They will remain faithful because none of them wants to cheat. They intend to honor their commitments. They will both be content to adhere to a schedule that they establish together. For them to be content, no wild and crazy adventures will be necessary. Virgo and Capricorn would much rather stay in their comfort zones because that is where they feel most at ease. Rather than a passionate relationship, they desire stability.",
            Pair("Capricorn", "Libra") to "The compatibility of Capricorn and Libra is low. The priorities and values of these two signs are different. Libras are very conscious of how other people perceive them. In the meantime, Capricorn doesn't give any thought about what people think. Despite their differences, these two signs are capable of making a relationship work if they work hard at it.",
            Pair("Capricorn", "Scorpio") to "They could be very close friends because of their similar personalities. They are both very devoted, after all. They'd go to great lengths to help a friend in distress. They would never abandon a person in need of assistance. They are also both focused and driven. They will succeed greatly if they collaborate on a project. They'll encourage one another to succeed. Scorpios tend to be possessive of the people in their lives, but since Capricorns are generally faithful, they shouldn't worry about it. Scorpios will follow along with passion and feedback from Capricorns who will take the initiative with fresh ideas. They will be an invincible team as long as they can master appropriate communication techniques and treat one another with respect at all times.",
            Pair("Capricorn", "Sagittarius") to "Their lifestyles are too dissimilar for a partnership to succeed. A Sagittarius, for instance, might prefer to go out every weekend, exploring new areas and having novel experiences. A Capricorn, on the other hand, will be happiest curled up with a good book in bed. They have no desire to leave their house. They would prefer to remain indoors and shut out the outside world.",
            Pair("Capricorn", "Capricorn") to "You can tell when a Capricorn and another Capricorn are in love by their energy and the way they look out for one another. This sign will be excellent at managing the family and business since they seek stability in all relationships, particularly financial stability. They are driven and have a strong feeling of duty to look after their spouse, family, and kids. Their goal is to take charge. They'll discover that their commitment to their joint obligations outweighs anything in the romance. Given that Capricorn is a cardinal sign—a sign known for its desire for initiative and authority—it seems likely that this may lead to some disagreements.",
            Pair("Capricorn", "Aquarius") to "Capricorn and Aquarius are not a good match for each other. When it comes to intimacy and romance, Aquarius is very fast, free-spirited, and open to trying new things, whereas Capricorn is quite conservative, sensible, and low-key. As long as they work things out when things get difficult, these two will band together and get along well. Whether or not they can make the relationship work is the basis for the lack of trust in the partnership. Given that Capricorn and Aquarius are both renowned for suppressing their emotions, a love connection will be quite difficult for them. They will need to genuinely accept one another's incapacity to communicate about their emotions if they want it to work.",
            Pair("Capricorn", "Pisces") to "Capricorn and Pisces have various reasons why they find it difficult to commit. Capricorns are cautious about opening their hearts to others. Moreover, Pisces are erratic and flighty. But Pisces are also tolerant. They are not critical of others. With a Pisces partner, Capricorns will feel comfortable being who they are. These two signs have the potential to gradually develop a solid partnership as long as they are patient with one another. With ease, they can go from strangers to friends to lovers.",

            Pair("Aquarius", "Aries") to "As friends or friends with benefits, Aries and Aquarius make a better combination than a possible love pair. Because of their shared ideals and outlook on life, Aries and Aquarius can actually get along well with each other. They just \"get\" one another. These two zodiac signs are naturally adept at conversing and establishing relationships. Both signs are intelligent, creative individuals who are always in need of stimulation. Both Aquarius and Aries enjoy engaging in debates, but Aquarius prefers to keep things reasonable and pragmatic, while Aries will get emotional and confrontational. Just be mindful of the fact that both Aries and Aquarius have strong tempers—Aries more so than Aquarius.",
            Pair("Aquarius", "Taurus") to "The compatibility between Taurus and Aquarius is extremely low. Seldom do these two signs get along. They are extremely different. They won't last as a pair if they can't compromise and be open to changing their minds when they disagree. They may not even remain friends.",
            Pair("Aquarius", "Gemini") to "Given that both of these signals entail emotional difficulties, there may be some challenges ahead.They don’t like to dwell on the way they are feeling and would rather push uncomfortable emotions deep down in their chest.  They won't hold it against each other, though, since they both find it difficult to be vulnerable. If there are a few secrets here and there, they'll understand. Additionally, they will be understanding if the other person isn't feeling inclined to discuss their problems. The partnership won't end because of the lack of communication.",
            Pair("Aquarius", "Cancer") to "Even though both signs like social situations, a Cancer will eventually wish to withdraw within their home, much like a crab does in its shell. An Aquarian will want to continue and stay outside in the interim. They both have the disposition to expect things to go their way. Whereas Aquarius will use their independence and knowledge to make decisions that work for them alone, Cancer will resort to manipulation. They must resolve their differences in order for their friendship to be strong.",
            Pair("Aquarius", "Leo") to "Despite having very different priorities, these two signs can nonetheless operate together in a friendship. Their differences simply cannot be allowed to get in the way of their relationship. They are really loyal to one other, after all. They would stop at nothing to help someone with whom they had a connection. Those they adore are zealously protected by them. These indicators are also quite aspirational. They don't give up on goals they set for themselves. They don't give up until they achieve their objectives.",
            Pair("Aquarius", "Virgo") to "If these two signs hope to maintain a love connection, they will need to put in a lot of effort. They will have to work at talking to each other and making concessions to one another. The relationship won't endure long if they let their stubbornness or tempers to get the better of them. These two signs do, after all, want to follow their own set of rules. Even their lover doesn't have the right to dictate to them what to do.",
            Pair("Aquarius", "Libra") to "These two signs of the zodiac are eager to discover the world's natural beauties. Libras and Aquarians like socializing with new people and expanding their knowledge of the cosmos. Their appetite for information and experience is strong. These two signs are social butterflies who will make great pals. When given the chance, Aquarius and Libra will never say no to a road trip, concert, or party. They'll be willing to try nearly anything. Their relationship will grow stronger with each adventure they embark on together.",
            Pair("Aquarius", "Scorpio") to "Due to their dissimilar characteristics, this zodiac couple isn't the strongest romantic duo. The unclear emotionally distant Aquarius will find Scorpio's emotions and possessiveness to be excessively intense. Their Aquarian spouse will not want to deal with their Scorpio partner's occasional clinginess and emotional outbursts; instead, their free-spirited nature and incapacity to communicate their feelings will allow them to pack up and walk on. They both need to put in a lot of effort and dedication, communicate their feelings, and have a strong foundation of trust for a romantic relationship to succeed.",
            Pair("Aquarius", "Sagittarius") to "Both Sagittarius and Aquarius are highly intelligent and cognizant of one another's characteristics. They are unparalleled in their dedication to understanding one another. While the Aquarius companion will contribute unique ideas and stimulating discourse, the Sagittarius partner will add warmth to the partnership. ",
            Pair("Aquarius", "Capricorn") to "Capricorn and Aquarius are not a good match for each other. When it comes to intimacy and romance, Aquarius is very fast, free-spirited, and open to trying new things, whereas Capricorn is quite conservative, sensible, and low-key. As long as they work things out when things get difficult, these two will band together and get along well. Whether or not they can make the relationship work is the basis for the lack of trust in the partnership. Given that Capricorn and Aquarius are both renowned for suppressing their emotions, a love connection will be quite difficult for them. They will need to genuinely accept one another's incapacity to communicate about their emotions if they want it to work.",
            Pair("Aquarius", "Aquarius") to "Now, two Aquarians may discover that they are not very compatible in a romantic relationship. More than any other sign of the zodiac, these two will be able to communicate with each other. It's possible that an Aquarian couple dating will get along better as friends than as love partners. Two Aquarian signs not only have a detached emotional relationship, but they also share a yearning for independence. They might as well avoid anything romantic and keep things amicable with this.",
            Pair("Aquarius", "Pisces") to "These two zodiac signs are idealists who wish to improve the state of the world. They will engage in thoughtful discussions on how they may influence society. But neither of them will do anything about it. They will not press one another to reach objectives. They won't even try to pursue their dreams—they will only talk about them. Both Pisces and Aquarius should have people that actively support them.",

            Pair("Pisces", "Aries") to "The compatibility between Pisces and Aries is quite low. It will be difficult for both of these signs to keep a connection continuing. They aren't emotionally compatible with one another. They may have engaging talks, but they won't be able to put their trust in one another or be open with one another. They will have to put in extra effort if they hope to succeed as a relationship.",
            Pair("Pisces", "Taurus") to "These two signs are a match made in heaven since they both place a high importance on deep emotional relationships. They find it difficult to part from someone once they become attached to them. They won't automatically want to leave if there is a problem. It will be to mend the connection, reach a compromise, and make apologies. ",
            Pair("Pisces", "Gemini") to "There is very little compatibility between Gemini and Pisces. These are some of the worst conceivable combinations of zodiac signs. Physically, intellectually, or emotionally, they are incompatible. They don't communicate well with each other. They will avoid talking about their emotions at all costs. ",
            Pair("Pisces", "Cancer") to "Cancers and Pisces have loyalty. They keep their word when they commit to someone. More importantly, they are at ease discussing everything and everything, so they will never run out of things to talk about. They'll talk about their futures, reveal their deepest fears, and share secrets. There aren’t any topics that are off limits when it comes to these two signs.",
            Pair("Pisces", "Leo") to "Because Leo Pisces pursues two very distinct kind of love, their partnership is incredibly flawed. Leo will seem to Pisces too detached from their feelings, while Pisces will perceive their Leo partner as too cut off from their own ambitions and strengths. The Pisces spouse will lack strength, confidence, and initiative, whereas Leo will come across as blunt, honest, and insensitive. In a Leo Pisces relationship, there will be a lot of miscommunication and disrespect, which will ultimately cause them to break up.",
            Pair("Pisces", "Virgo") to "Virgos benefit from the influence of Pisces. They can greatly improve a Virgo's ability to connect with their emotions. Virgos, after all, have a nasty habit of ignoring unpleasant emotions and diverting their attention with activity. But a Pisces will demonstrate to a Virgo that they don't need to isolate oneself in order to be safe. A Virgo will be encouraged by a Pisces to be much more open and at ease with their own feelings.",
            Pair("Pisces", "Libra") to "These signs don't go together well. They will hold a lot of their emotions, both positive and negative, inside. They'll never be aware of the other person's thoughts. It gets worse: they won't be able to put their trust in one another. Libras are flirts after all. They enchant everyone they come into contact with. This will not sit well with a Pisces. Pisces seeks a mate who will refrain from making fun of them. They are looking for a mate that is 100 percent devoted.",
            Pair("Pisces", "Scorpio") to "Both of these signs have a desire for commitment and long-term relationships. Their only desire is to find their soul partner and settle down to enjoy life. Their shared goals in life and their effective communication skills make them a great combination. They have enough faith in one another, to be honest with one another about their feelings and ideas, which is not usually the case with Scorpios. When they are with the wrong person, they will withdraw, but when they are with Pisces, they will feel secure enough to be vulnerable.",
            Pair("Pisces", "Sagittarius") to "Given that Sagittarius and Pisces are two fluid signs, it's possible that they will be excellent friends while having different underlying identities. While both Sagittarius and Pisces possess an analytical and philosophical mind, Sagittarius prefers to be free to jump right into new challenges, while Pisces prefers to go a little bit further into their fantasies. Sagittarius only considers the larger picture that is directly in front of them, whereas Pisces looks to the future.",
            Pair("Pisces", "Capricorn") to "Capricorn and Pisces have various reasons why they find it difficult to commit. Capricorns are cautious about opening their hearts to others. Moreover, Pisces are erratic and flighty. But Pisces are also tolerant. They are not critical of others. With a Pisces partner, Capricorns will feel comfortable being who they are. These two signs have the potential to gradually develop a solid partnership as long as they are patient with one another. With ease, they can go from strangers to friends to lovers.",
            Pair("Pisces", "Aquarius") to "These two zodiac signs are idealists who wish to improve the state of the world. They will engage in thoughtful discussions on how they may influence society. But neither of them will do anything about it. They will not press one another to reach objectives. They won't even try to pursue their dreams—they will only talk about them. Both Pisces and Aquarius should have people that actively support them.",
            Pair("Pisces", "Pisces") to "Pisces and Pisces get along well. Because they have similar interests and ideals, these signs complement each other effectively. But they could find it difficult to express their emotions to one another. They never put themselves first, therefore they won't get accustomed to their partner's attention. Since they are accustomed to giving rather than receiving, they will find the act of affection awkward at first. But Pisces Pisces love should last over time.",


        )

        return detailsMap[Pair(firstSign, secondSign)]
    }

    //incharge of displaying info when button2 is clicked
    private fun showDetails() {
        //value to get the details that will be put in
        val firstSign = binding.Spinner1.selectedItem.toString()
        val secondSign = binding.Spinner2.selectedItem.toString()
        val score = CompatibilityScore(firstSign, secondSign)
        val details = CompatibilityDetails(firstSign, secondSign)

        //layout of the info
        //opens in another page
        val intent = Intent(this, InfoActivity::class.java).apply {
            putExtra("firstSign", firstSign)
            putExtra("secondSign", secondSign)
            putExtra("score", score)
            putExtra("details", details)
        }
        startActivity(intent)//opens next page
    }
}



